try:
    raise ValueError('teste')
except Exception as e:
    print(e)